# Generated by Django 2.2.7 on 2019-11-30 11:00

import datapane.core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csvfile', models.FileField(upload_to=datapane.core.models.get_file_path, validators=[django.core.validators.FileExtensionValidator(['csv'])], verbose_name='CSV file')),
            ],
        ),
    ]
